"""initial schema

Revision ID: ab01e3d7f42a
Revises: 
Create Date: 2026-05-19 11:18:40.172699

"""
from typing import Sequence, Union

# from alembic import op
# import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab01e3d7f42a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
