name: CI

on:

  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main


jobs:

  backend-test:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"


      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Ruff
        run: |
          ruff check .

      - name: Run tests
        env:
          SECRET_KEY: test-secret
          ALGORITHM: HS256
          DATABASE_URL: sqlite:///./test.db
          CORS_ORIGINS: http://localhost:5173
        run: |
          pytest



  backend-docker:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Build Docker image
        run: |
          docker build -t splitwise-backend ./backend
    
  frontend-test:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: |
          npm ci

      - name: Build Frontend
        run: |
          npm run build

  frontend-docker:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Frontend Docker Image
        run: |
          docker build -t splitwise-frontend ./frontend